[app]
# Pexels API Key 
# Register at https://www.pexels.com/api/ to get your API key.
# You can use multiple keys to avoid rate limits.
# For example: pexels_api_keys = ["123456789","abcdefghi"]
pexels_api_keys = ["zq1XRtia7imGXx4xFNA7oZtxJlOZagfHQKexoM4NcLKyGJr5SWidXhw8"]

# OpenAI API Key
# Visit https://openai.com/api/ for details on obtaining an API key.
openai_api_key = "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"
openai_base_url = ""
openai_model_name = "gpt-3.5-turbo"

# Subtitle Provider, "edge" or "whisper"
# If empty, the subtitle will not be generated
subtitle_provider = "edge"

[whisper]
# Only effective when subtitle_provider is "whisper"

# Run on GPU with FP16
# model = WhisperModel(model_size, device="cuda", compute_type="float16")

# Run on GPU with INT8
# model = WhisperModel(model_size, device="cuda", compute_type="int8_float16")

# Run on CPU with INT8
# model = WhisperModel(model_size, device="cpu", compute_type="int8")

# recommended model_size: "large-v3"
model_size = "large-v3"
# if you want to use GPU, set device="cuda"
device = "CPU"
compute_type = "int8"
[pexels]
[pexels.proxies]
### Use a proxy to access the Pexels API
### Format: "http://<username>:<password>@<proxy>:<port>"
### Example: "http://user:pass@proxy:1234"
### Doc: https://requests.readthedocs.io/en/latest/user/advanced/#proxies
http = "http://127.0.0.1:54928"
https = "http://127.0.0.1:54928"
